export const site = {
  name: 'Rohith Arumugam Suresh',
  shortName: 'ROHITH',
  playerTag: 'PORTFOLIO',
  cabinetTitle: 'ROHITH BUILDS',
  tagline: 'I like building systems from the ground up and finding out where they break.',
  insertCoin: 'CMU MCDS · Pittsburgh, PA',
  marquee:
    'I work on distributed systems, databases, streaming, and applied machine learning.',
  email: 'rohithas@andrew.cmu.edu',
  phone: '(412) 807-0975',
  location: 'Pittsburgh, PA',
  links: {
    github: 'https://github.com/rohitharumugams',
    linkedin: 'https://www.linkedin.com/in/rohith-as/',
    resume: '/resume.pdf',
  },
  education: [
    {
      school: 'Carnegie Mellon University',
      place: 'Pennsylvania, US',
      degree: 'Master of Computational Data Science',
      when: 'Dec 2027',
      detail: 'GPA 4.00/4.00',
    },
    {
      school: 'Sri Sivasubramaniya Nadar College of Engineering',
      place: 'Chennai, Tamil Nadu',
      degree: 'B.E. Computer Science & Engineering',
      when: 'Apr 2026',
      detail: 'GPA 8.37/10.00',
    },
  ],
  loadout: [
    'Python',
    'C++',
    'FastAPI',
    'Docker',
    'SQL',
    'FFmpeg',
    'LoRA',
    'OpenCV',
    'DuckDB',
    'Git',
  ],
  unlocks: [
    'Amazon Summer School 2025 — top 5% of 60k+',
    'UN Academic Impact Campus Director — 25 fellows',
    'SSN Coding Club ML Deputy Lead — team of 6',
  ],
  bio: [
    "I'm Rohith, a graduate student at Carnegie Mellon who enjoys building systems end to end.",
    'Most of my work starts with a question I want to understand properly: how an object store should react to changing access patterns, what a database needs beneath SQL, or whether synthetic roadside audio can improve a real model.',
    'I care about measurements, failure cases, and being clear about what a project can and cannot do.',
  ],
} as const
