export const site = {
  name: 'Rohith Arumugam Suresh',
  shortName: 'ROHITH',
  playerTag: 'PLAYER 1',
  cabinetTitle: 'SYSTEMS QUEST',
  tagline: 'Clear the stage. Measure the score. Ship the build.',
  insertCoin: 'CMU MCDS · Pittsburgh · Insert curiosity',
  email: 'rohithas@andrew.cmu.edu',
  phone: '(412) 807-0975',
  location: 'Pittsburgh, PA',
  links: {
    github: 'https://github.com/rohitharumugams',
    linkedin: 'https://www.linkedin.com/in/rohith-as/',
    resume: '/resume.pdf',
  },
  education: [
    {
      school: 'Carnegie Mellon University',
      place: 'Pennsylvania, US',
      degree: 'Master of Computational Data Science',
      when: 'Dec 2027',
      detail: 'GPA 4.00/4.00',
    },
    {
      school: 'Sri Sivasubramaniya Nadar College of Engineering',
      place: 'Chennai, Tamil Nadu',
      degree: 'B.E. Computer Science & Engineering',
      when: 'Apr 2026',
      detail: 'GPA 8.37/10.00',
    },
  ],
  loadout: [
    'Python',
    'C++',
    'FastAPI',
    'Docker',
    'SQL',
    'FFmpeg',
    'LoRA',
    'OpenCV',
    'DuckDB',
    'Redis vibes (DIY logs)',
  ],
  unlocks: [
    'Amazon Summer School 2025 — top 5% of 60k+',
    'UN Academic Impact Campus Director — 25 fellows',
    'SSN Coding Club ML Deputy Lead — team of 6',
  ],
  bio: [
    'Not a highlight reel of course titles — a cabinet of things that run.',
    'Distributed stores, homemade databases, event logs, adaptive video, RAG agents that actually place orders, and a Doppler physics sim for roadside audio.',
    'If it does not have a scoreboard or a failure mode, it is still cooking.',
  ],
} as const
